export ENHANCD_ENABLE_HYPHEN=false
export ENHANCD_ENABLE_DOUBLE_DOT=false
export ENHANCD_ENABLE_SINGLE_DOT=false
export ENHANCD_ENABLE_HOME=true
export ENHANCD_USE_ABBREV=true

export ENHANCD_ARG_HYPHEN=--
export ENHANCD_ARG_DOUBLE_DOT=...
export ENHANCD_ARG_HOME=''
export ENHANCD_DOT_SHOW_FULLPATH=1
export ENHANCD_USE_FUZZY_MATCH=0

compdef _cd __enhancd::cd
